server:
  port: 80

jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
  user: root
  password: Yan1996>

#mybatis
mybatis_config_file:   mybatis-config.xml
mybatis_mapper_path:  /mapper/**.xml
entity_package: cn.smileyan.demo.entity

